### ISSUE TITLE
This url is not available or conflicts with the already installed app(s):

### ISSUE THREAD

**Issue by icf20** [YunoHost-Apps/portainer_ynh#16]
`This url is not available or conflicts with the already installed app(s):`

it look like this app install in /

**Comment by louismerlin** [comment]
I have the same problem... Portainer can only be installed alone :sweat_smile:

**Comment by buz01** [comment]
The same here...

**Comment by ashledombos** [comment]
You need to create a subdomain, like portainer.mydomain.tld .

**Comment by alexAubin** [comment]
This is not an issue with portainer ... You need to install this app on a dedicated domain or subdomain...
