### ISSUE TITLE
doesn't install.

### ISSUE THREAD

**Issue by Mrs-Feathers** [YunoHost-Apps/portainer_ynh#18]
i don't know what happened. there's no real text to show me what its doing to install.. so after clicking install, about 30 minutes later, it says 504 error api not responding. there's no real text or anything on the installer screen after you click the install button so its not like i can give you an error message or show anything useful. :( it just won't install.

**Comment by ashledombos** [comment]
Hi @MothGirlMusic 

Maybe try with command line.

First be sure to remove the package

`yunohost app remove portainer`

then install with debug activated:

`yunohost app install portainer --debug`

maybe there'll be a useful output.

**Comment by Mrs-Feathers** [comment]
hi thanks! i removed it like you said then installed it and this time i guess it worked! no idea what happened. no errors. cheers! i love portainer and docker in my YunoHost!


----
73, KC1KSG

**Comment by ashledombos** [comment]
HI @MothGirlMusic is it possible to close this issue? As I'm no maintainer of this app, I can't do it but as creator of the issue you should be able to do it.
