### ISSUE TITLE
Your app is out of date on the community list

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/portainer_ynh#7]
Hello,

The [community list](https://github.com/YunoHost/apps/blob/master/community.json) uses an old commit for your app.
Since your app has some corrections, would you please update the community list if possible.

For the Apps group.

**Comment by aymhce** [comment]
Hello, ok, I'm waiting the new app's build and passing the jenkins pipeline

**Comment by alexAubin** [comment]
Bumpitybump :slightly_smiling_face: 

I found that the commit on [community.json](https://github.com/YunoHost/apps/blob/master/community.json) is outdated, hence people installing the app via this list won't benefit from the last upgrades / improvements ...

Please create a PR to update it on the list (I do not maintain this app so it's not relevant for me to do it and it might be refused...)

ProTip™ : possibly you can now set the commit to 'HEAD', to use the latest commit of master automatically in the future. If you do this, it is strongly recommended to use a 'testing' branch for changes that are not deemed stable yet.
