### ISSUE TITLE
Yunohost 3.0 :  Invalid credentials 

### ISSUE THREAD

**Issue by guiguid** [YunoHost-Apps/portainer_ynh#8]
Hi, 
After creating admin user, I can't connect with any users even just created admin !
 Invalid credentials 
Fresh Yunohost install
Fresh Protainer install in dedicaded sub domain 'docker.my.domain.com'

yunohost
    3.0.0.1 (stable)
yunohost-admin
    3.0.0 (stable)
moulinette
    3.0.0 (stable)
ssowat
    3.0.0 (stable)

**Comment by 4abhinavjain** [comment]
Did you manage to resolve it?

**Comment by aymhce** [comment]
@guiguid @4abhinavjain will work on it !

**Comment by aymhce** [comment]
resolv on last version

**Comment by 4abhinavjain** [comment]
@aymhce thanks for the fix
